#!/usr/bin/env python3

# NOTE: this front-end was mostly generated by claude

import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, Gdk, GObject, Gio
import json
import os
import subprocess

CONFIG_PATH = os.path.join(
    os.environ.get('XDG_CONFIG_HOME', os.path.expanduser('~/.config')),
    'url-handler', 'config.json'
)
MATCHERS = ["startswith", "contains", "endswith", "regex"]
MATCHER_LABELS = ["Starts with", "Contains", "Ends with", "Matches regex"]


def load_config():
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    try:
        with open(CONFIG_PATH) as f:
            return json.load(f)
    except FileNotFoundError:
        return {"default": {"exec": ""}, "handlers": []}


def save_config(config):
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    with open(CONFIG_PATH, 'w') as f:
        json.dump(config, f, indent=2)


def app_info_to_exec(app_info):
    cmdline = app_info.get_commandline()
    return cmdline


def _get_icon_name(icon_obj):
    if not icon_obj:
        return None
    try:
        if isinstance(icon_obj, Gio.ThemedIcon):
            names = icon_obj.get_names()
            return names[0] if names else None
    except Exception:
        pass
    return None


def _collect_apps_local():
    apps = []
    for app in Gio.AppInfo.get_all():
        if not app.get_commandline():
            continue
        apps.append({
            'name': app.get_display_name(),
            'icon': _get_icon_name(app.get_icon()),
            'exec': app_info_to_exec(app),
        })
    return sorted(apps, key=lambda a: a['name'].lower())


def _collect_apps_host():
    script = r"""
import gi
gi.require_version('Gio', '2.0')
from gi.repository import Gio
import json, re

def to_exec(cmd):
    cmd = re.sub(r'\s*%[uUfF]\s*', ' %u', cmd)
    return re.sub(r'%[a-zA-Z]', '', cmd).strip()

def get_icon(app):
    icon_obj = app.get_icon()
    if not icon_obj:
        return None
    try:
        if isinstance(icon_obj, Gio.ThemedIcon):
            names = icon_obj.get_names()
            return names[0] if names else None
    except Exception:
        pass
    return None

apps = []
for a in Gio.AppInfo.get_all():
    cmd = a.get_commandline()
    if not cmd:
        continue
    apps.append({'name': a.get_display_name(), 'icon': get_icon(a), 'exec': to_exec(cmd)})

apps.sort(key=lambda a: a['name'].lower())
print(json.dumps(apps))
"""
    try:
        result = subprocess.run(
            ['flatpak-spawn', '--host', 'python3', '-c', script],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
    except Exception:
        pass
    return []

apps = _collect_apps_host() if os.path.exists('/.flatpak-info') else _collect_apps_local()


class AppItem(GObject.Object):
    __gtype_name__ = 'AppItem'
    name = GObject.Property(type=str, default='')
    icon = GObject.Property(type=str, default='')
    exec_str = GObject.Property(type=str, default='')

    def __init__(self, name, icon_name, exec_str):
        super().__init__(name=name, icon=icon_name or '', exec_str=exec_str)


apps_store = Gio.ListStore(item_type=AppItem)
for _app in apps:
    apps_store.append(AppItem(_app['name'], _app.get('icon'), _app['exec']))


def _make_app_factory():
    factory = Gtk.SignalListItemFactory()

    def setup(_, list_item):
        box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        img = Gtk.Image()
        img.set_pixel_size(16)
        box.append(img)
        label = Gtk.Label(xalign=0)
        box.append(label)
        list_item.set_child(box)

    def bind(_, list_item):
        box = list_item.get_child()
        img = box.get_first_child()
        label = img.get_next_sibling()
        item = list_item.get_item()
        img.set_from_icon_name(item.icon or 'application-x-executable')
        label.set_text(item.name[:40]) # TODO use proper label truncation

    factory.connect('setup', setup)
    factory.connect('bind', bind)
    return factory


class HandlerRow(Adw.ExpanderRow):
    def __init__(self, handler, on_delete, on_reorder, on_change):
        super().__init__()
        self.set_title_lines(1)
        self.set_subtitle_lines(1)
        self._on_delete = on_delete
        self._on_reorder = on_reorder
        self._on_change = on_change
        self._setup(handler)

    def _setup(self, handler):
        handle = Gtk.Image(icon_name="list-drag-handle-symbolic")
        handle.add_css_class("dim-label")
        handle.set_margin_start(2)
        handle.set_cursor_from_name("grab")
        drag_src = Gtk.DragSource(actions=Gdk.DragAction.MOVE)
        drag_src.connect("prepare", self._on_drag_prepare)
        handle.add_controller(drag_src)
        self.add_prefix(handle)

        # Drop target covers the whole row
        drop_tgt = Gtk.DropTarget.new(GObject.TYPE_OBJECT, Gdk.DragAction.MOVE)
        drop_tgt.connect("drop", self._on_drop)
        self.add_controller(drop_tgt)

        # Match type — values set before signals are connected so they don't fire _on_change
        self._matcher_row = Adw.ComboRow(title="Match type")
        self._matcher_row.set_model(Gtk.StringList.new(MATCHER_LABELS))
        self._matcher_row.set_selected(MATCHERS.index(handler.get("matcher", "startswith")))
        self._matcher_row.connect("notify::selected", self._on_field_changed)
        self.add_row(self._matcher_row)

        self._pattern_row = Adw.EntryRow(title="URL pattern")
        self._pattern_row.set_text(handler.get("pattern", ""))
        self._pattern_row.connect("changed", self._on_field_changed)
        self.add_row(self._pattern_row)

        self._app_row = Adw.ComboRow(title="Open with")
        self._app_row.set_model(apps_store)
        self._app_row.set_expression(Gtk.PropertyExpression.new(AppItem, None, 'name'))
        self._app_row.set_factory(_make_app_factory())
        self._app_row.set_enable_search(True)

        exec_saved = handler.get("exec", "")
        for i, app_dict in enumerate(apps):
            if app_dict['exec'] == exec_saved:
                self._app_row.set_selected(i)
                break

        self._app_row.connect("notify::selected", self._on_field_changed)
        self.add_row(self._app_row)

        del_btn = Gtk.Button(icon_name="user-trash-symbolic")
        del_btn.set_valign(Gtk.Align.CENTER)
        del_btn.add_css_class("flat")
        del_btn.connect("clicked", lambda _: self._on_delete(self))
        self.add_suffix(del_btn)

        self._sync_title()

    def _on_drag_prepare(self, src, x, y):
        val = GObject.Value()
        val.init(GObject.TYPE_OBJECT)
        val.set_object(self)
        return Gdk.ContentProvider.new_for_value(val)

    def _on_drop(self, tgt, value, x, y):
        if isinstance(value, HandlerRow) and value is not self:
            self._on_reorder(value, self)
        return True

    def _on_field_changed(self, *_):
        self._sync_title()
        self._on_change()

    def _sync_title(self, *_):
        idx = self._matcher_row.get_selected()
        label = MATCHER_LABELS[idx] if idx < len(MATCHER_LABELS) else ""
        pattern = self._pattern_row.get_text()
        self.set_title(f'{label} "{pattern}"' if pattern else "(new rule)")
        item = self._app_row.get_selected_item()
        self.set_subtitle(('Open with ' + item.name) if item else "")

    def get_data(self):
        item = self._app_row.get_selected_item()
        return {
            "matcher": MATCHERS[self._matcher_row.get_selected()],
            "pattern": self._pattern_row.get_text(),
            "exec": item.exec_str if item else "",
        }


class SettingsWindow(Adw.ApplicationWindow):
    def __init__(self, config, **kwargs):
        super().__init__(**kwargs)
        self.set_title("URL Handler Configuration")
        self.set_default_size(640, 560)
        self._handler_rows = []
        self._build(config)

    def _build(self, config):
        self._toast_overlay = Adw.ToastOverlay()
        toolbar_view = Adw.ToolbarView()

        header = Adw.HeaderBar()
        self._save_btn = Gtk.Button(label="Save")
        self._save_btn.add_css_class("suggested-action")
        self._save_btn.set_sensitive(False)
        self._save_btn.connect("clicked", self._on_save)
        header.pack_end(self._save_btn)
        toolbar_view.add_top_bar(header)

        scroll = Gtk.ScrolledWindow(vexpand=True)
        scroll.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)

        page = Adw.PreferencesPage()

        default_group = Adw.PreferencesGroup(
            title="Default Browser",
            description="Used for URLs not handled by an app",
        )
        self._app_row = Adw.ComboRow(title="Open with")
        self._app_row.set_model(apps_store)
        self._app_row.set_expression(Gtk.PropertyExpression.new(AppItem, None, 'name'))
        self._app_row.set_factory(_make_app_factory())
        self._app_row.set_enable_search(True)

        exec_saved = config.get('default', '').get("exec", "")
        for i, app_dict in enumerate(apps):
            if app_dict['exec'] == exec_saved:
                self._app_row.set_selected(i)
                break

        self._app_row.connect("notify::selected", self._mark_dirty)

        default_group.add(self._app_row)
        page.add(default_group)

        self._rules_group = Adw.PreferencesGroup(
            title="Application URL Handlers",
            description="The first match will be used",
        )
        add_btn = Gtk.Button(icon_name="list-add-symbolic")
        add_btn.add_css_class("flat")
        add_btn.set_tooltip_text("Add rule")
        add_btn.connect("clicked", self._on_add_rule)
        self._rules_group.set_header_suffix(add_btn)

        for h in config.get("handlers", []):
            self._append_row(h)

        page.add(self._rules_group)
        scroll.set_child(page)
        toolbar_view.set_content(scroll)
        self._toast_overlay.set_child(toolbar_view)
        self.set_content(self._toast_overlay)

    def _mark_dirty(self, *_):
        self._save_btn.set_sensitive(True)

    def _append_row(self, handler=None):
        row = HandlerRow(
            handler or {"matcher": "startswith", "pattern": "", "exec": ""},
            self._remove_row,
            self._reorder_row,
            self._mark_dirty,
        )
        self._handler_rows.append(row)
        self._rules_group.add(row)

    def _on_add_rule(self, _):
        self._append_row()
        self._mark_dirty()

    def _remove_row(self, row):
        self._handler_rows.remove(row)
        self._rules_group.remove(row)
        self._mark_dirty()

    def _reorder_row(self, dragged, target):
        src_idx = self._handler_rows.index(dragged)
        dst_idx = self._handler_rows.index(target)
        self._handler_rows.insert(dst_idx, self._handler_rows.pop(src_idx))
        for row in list(self._handler_rows):
            self._rules_group.remove(row)
        for row in self._handler_rows:
            self._rules_group.add(row)
        self._mark_dirty()

    def _on_save(self, *_):
        item = self._app_row.get_selected_item()
        config = {
            "default": {"exec": item.exec_str if item else ""},
            "handlers": [r.get_data() for r in self._handler_rows],
        }
        save_config(config)
        self._save_btn.set_sensitive(False)
        self._toast_overlay.add_toast(Adw.Toast.new("Configuration saved"))


class URLHandlerSettingsApp(Adw.Application):
    def __init__(self):
        super().__init__(application_id="net.sowgro.URLHandler.Configuration")
        self.connect("activate", self._on_activate)

    def _on_activate(self, _):
        SettingsWindow(config=load_config(), application=self).present()


if __name__ == "__main__":
    URLHandlerSettingsApp().run()
