#!/usr/bin/env python3

# NOTE: this front-end was mostly generated by claude

import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, Gdk, GObject, Gio, GLib
import json
import os
import re
import subprocess
import threading

CONFIG_PATH = os.path.join(
    os.environ.get('XDG_CONFIG_HOME', os.path.expanduser('~/.config')),
    'url-handler', 'config.json'
)
MATCHERS = ["startswith", "contains", "endswith"]
MATCHER_LABELS = ["Starts with", "Contains", "Ends with"]


def load_config():
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    try:
        with open(CONFIG_PATH) as f:
            return json.load(f)
    except FileNotFoundError:
        return {"default": {"exec": ""}, "handlers": []}


def save_config(config):
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    with open(CONFIG_PATH, 'w') as f:
        json.dump(config, f, indent=2)


def app_info_to_exec(app_info):
    cmdline = app_info.get_commandline() or (app_info.get_executable() + ' %U')
    # Replace desktop-file URL/file field codes with the %u placeholder url-handler.py expects
    cmdline = re.sub(r'\s*%[uUfF]\s*', ' %u', cmdline)
    cmdline = re.sub(r'%[a-zA-Z]', '', cmdline).strip()
    return cmdline


def _get_icon_name(icon_obj):
    if not icon_obj:
        return None
    try:
        if isinstance(icon_obj, Gio.ThemedIcon):
            names = icon_obj.get_names()
            return names[0] if names else None
    except Exception:
        pass
    return None


def _collect_apps_local():
    apps = []
    for app in Gio.AppInfo.get_all():
        if not app.get_commandline():
            continue
        apps.append({
            'name': app.get_display_name(),
            'icon': _get_icon_name(app.get_icon()),
            'exec': app_info_to_exec(app),
        })
    return sorted(apps, key=lambda a: a['name'].lower())


def _collect_apps_host():
    script = r"""
import gi
gi.require_version('Gio', '2.0')
from gi.repository import Gio
import json, re

def to_exec(cmd):
    cmd = re.sub(r'\s*%[uUfF]\s*', ' %u', cmd)
    return re.sub(r'%[a-zA-Z]', '', cmd).strip()

def get_icon(app):
    icon_obj = app.get_icon()
    if not icon_obj:
        return None
    try:
        if isinstance(icon_obj, Gio.ThemedIcon):
            names = icon_obj.get_names()
            return names[0] if names else None
    except Exception:
        pass
    return None

apps = []
for a in Gio.AppInfo.get_all():
    cmd = a.get_commandline()
    if not cmd:
        continue
    apps.append({'name': a.get_display_name(), 'icon': get_icon(a), 'exec': to_exec(cmd)})

apps.sort(key=lambda a: a['name'].lower())
print(json.dumps(apps))
"""
    try:
        result = subprocess.run(
            ['flatpak-spawn', '--host', 'python3', '-c', script],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
    except Exception:
        pass
    return []


class _AppChooserWindow(Gtk.Window):
    def __init__(self, parent, on_chosen):
        super().__init__(title="Choose Application")
        self.set_transient_for(parent)
        self.set_modal(True)
        self.set_default_size(420, 540)
        self._on_chosen = on_chosen
        self._search_text = ""
        self._build()
        threading.Thread(target=self._load_apps, daemon=True).start()

    def _build(self):
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)

        header = Adw.HeaderBar()
        cancel_btn = Gtk.Button(label="Cancel")
        cancel_btn.connect("clicked", lambda _: self.close())
        header.pack_start(cancel_btn)
        self._select_btn = Gtk.Button(label="Select")
        self._select_btn.add_css_class("suggested-action")
        self._select_btn.set_sensitive(False)
        self._select_btn.connect("clicked", self._on_select)
        header.pack_end(self._select_btn)
        box.append(header)

        self._search_entry = Gtk.SearchEntry()
        self._search_entry.set_margin_start(8)
        self._search_entry.set_margin_end(8)
        self._search_entry.set_margin_top(4)
        self._search_entry.set_margin_bottom(4)
        self._search_entry.connect("search-changed", self._on_search)
        self._search_entry.set_sensitive(False)
        box.append(self._search_entry)

        self._stack = Gtk.Stack()

        spinner_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self._spinner = Gtk.Spinner()
        self._spinner.set_size_request(32, 32)
        self._spinner.set_halign(Gtk.Align.CENTER)
        self._spinner.set_valign(Gtk.Align.CENTER)
        self._spinner.set_vexpand(True)
        self._spinner.start()
        spinner_box.append(self._spinner)
        self._stack.add_named(spinner_box, "loading")

        scroll = Gtk.ScrolledWindow(vexpand=True)
        scroll.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        self._listbox = Gtk.ListBox()
        self._listbox.add_css_class("boxed-list")
        self._listbox.set_selection_mode(Gtk.SelectionMode.SINGLE)
        self._listbox.set_filter_func(self._filter_func)
        self._listbox.connect("row-selected", self._on_row_selected)
        self._listbox.connect("row-activated", self._on_row_activated)
        scroll.set_child(self._listbox)
        self._stack.add_named(scroll, "list")

        self._stack.set_visible_child_name("loading")
        box.append(self._stack)
        self.set_child(box)

    def _load_apps(self):
        apps = _collect_apps_host() if os.path.exists('/.flatpak-info') else _collect_apps_local()
        GLib.idle_add(self._populate, apps)

    def _populate(self, apps):
        for app in apps:
            row = Gtk.ListBoxRow()
            row._app_exec = app['exec']
            row._app_name = app['name']
            hbox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=12)
            hbox.set_margin_start(12)
            hbox.set_margin_end(12)
            hbox.set_margin_top(8)
            hbox.set_margin_bottom(8)
            img = Gtk.Image.new_from_icon_name(app.get('icon') or 'application-x-executable')
            img.set_pixel_size(32)
            hbox.append(img)
            label = Gtk.Label(label=app['name'], xalign=0, hexpand=True)
            hbox.append(label)
            row.set_child(hbox)
            self._listbox.append(row)
        self._spinner.stop()
        self._search_entry.set_sensitive(True)
        self._stack.set_visible_child_name("list")

    def _on_search(self, entry):
        self._search_text = entry.get_text().lower()
        self._listbox.invalidate_filter()

    def _filter_func(self, row):
        if not self._search_text:
            return True
        return self._search_text in getattr(row, '_app_name', '').lower()

    def _on_row_selected(self, listbox, row):
        self._select_btn.set_sensitive(row is not None)

    def _on_row_activated(self, listbox, row):
        self._on_chosen(row._app_exec)
        self.close()

    def _on_select(self, _):
        row = self._listbox.get_selected_row()
        if row:
            self._on_chosen(row._app_exec)
            self.close()


def open_app_chooser(parent_win, on_chosen):
    _AppChooserWindow(parent_win, on_chosen).present()


class HandlerRow(Adw.ExpanderRow):
    def __init__(self, handler, on_delete, on_reorder, on_change):
        super().__init__()
        self.set_title_lines(1)
        self.set_subtitle_lines(1)
        self._on_delete = on_delete
        self._on_reorder = on_reorder
        self._on_change = on_change
        self._setup(handler)

    def _setup(self, handler):
        handle = Gtk.Image(icon_name="list-drag-handle-symbolic")
        handle.add_css_class("dim-label")
        handle.set_margin_start(2)
        handle.set_cursor_from_name("grab")
        drag_src = Gtk.DragSource(actions=Gdk.DragAction.MOVE)
        drag_src.connect("prepare", self._on_drag_prepare)
        handle.add_controller(drag_src)
        self.add_prefix(handle)

        # Drop target covers the whole row
        drop_tgt = Gtk.DropTarget.new(GObject.TYPE_OBJECT, Gdk.DragAction.MOVE)
        drop_tgt.connect("drop", self._on_drop)
        self.add_controller(drop_tgt)

        # Match type — values set before signals are connected so they don't fire _on_change
        self._matcher_row = Adw.ComboRow(title="Match type")
        self._matcher_row.set_model(Gtk.StringList.new(MATCHER_LABELS))
        self._matcher_row.set_selected(MATCHERS.index(handler.get("matcher", "startswith")))
        self._matcher_row.connect("notify::selected", self._on_field_changed)
        self.add_row(self._matcher_row)

        self._pattern_row = Adw.EntryRow(title="URL pattern")
        self._pattern_row.set_text(handler.get("pattern", ""))
        self._pattern_row.connect("changed", self._on_field_changed)
        self.add_row(self._pattern_row)

        self._exec_row = Adw.EntryRow(title="Command (URL placeholder: %u)")
        self._exec_row.set_text(handler.get("exec", ""))
        self._exec_row.connect("changed", self._on_field_changed)
        pick_btn = Gtk.Button(icon_name="application-x-executable-symbolic")
        pick_btn.set_valign(Gtk.Align.CENTER)
        pick_btn.add_css_class("flat")
        pick_btn.set_tooltip_text("Choose application")
        pick_btn.connect("clicked", lambda _: open_app_chooser(
            self.get_root(), self._exec_row.set_text
        ))
        self._exec_row.add_suffix(pick_btn)
        self.add_row(self._exec_row)

        del_btn = Gtk.Button(icon_name="user-trash-symbolic")
        del_btn.set_valign(Gtk.Align.CENTER)
        del_btn.add_css_class("flat")
        del_btn.connect("clicked", lambda _: self._on_delete(self))
        self.add_suffix(del_btn)

        self._sync_title()

    def _on_drag_prepare(self, src, x, y):
        val = GObject.Value()
        val.init(GObject.TYPE_OBJECT)
        val.set_object(self)
        return Gdk.ContentProvider.new_for_value(val)

    def _on_drop(self, tgt, value, x, y):
        if isinstance(value, HandlerRow) and value is not self:
            self._on_reorder(value, self)
        return True

    def _on_field_changed(self, *_):
        self._sync_title()
        self._on_change()

    def _sync_title(self, *_):
        idx = self._matcher_row.get_selected()
        label = MATCHER_LABELS[idx] if idx < len(MATCHER_LABELS) else ""
        pattern = self._pattern_row.get_text()
        self.set_title(f'{label} "{pattern}"' if pattern else "(new rule)")
        self.set_subtitle(self._exec_row.get_text())

    def get_data(self):
        return {
            "matcher": MATCHERS[self._matcher_row.get_selected()],
            "pattern": self._pattern_row.get_text(),
            "exec": self._exec_row.get_text(),
        }


class SettingsWindow(Adw.ApplicationWindow):
    def __init__(self, config, **kwargs):
        super().__init__(**kwargs)
        self.set_title("URL Handler Configuration")
        self.set_default_size(640, 560)
        self._handler_rows = []
        self._build(config)

    def _build(self, config):
        self._toast_overlay = Adw.ToastOverlay()
        toolbar_view = Adw.ToolbarView()

        header = Adw.HeaderBar()
        self._save_btn = Gtk.Button(label="Save")
        self._save_btn.add_css_class("suggested-action")
        self._save_btn.set_sensitive(False)
        self._save_btn.connect("clicked", self._on_save)
        header.pack_end(self._save_btn)
        toolbar_view.add_top_bar(header)

        scroll = Gtk.ScrolledWindow(vexpand=True)
        scroll.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)

        page = Adw.PreferencesPage()

        default_group = Adw.PreferencesGroup(
            title="Default Browser",
            description="Used for URLs not handled by an app",
        )
        self._default_exec_row = Adw.EntryRow(title="Command (URL placeholder: %u)")
        self._default_exec_row.set_text(config.get("default", {}).get("exec", ""))
        pick_btn = Gtk.Button(icon_name="application-x-executable-symbolic")
        pick_btn.set_valign(Gtk.Align.CENTER)
        pick_btn.add_css_class("flat")
        pick_btn.set_tooltip_text("Choose application")
        pick_btn.connect("clicked", lambda _: open_app_chooser(
            self, self._default_exec_row.set_text
        ))
        self._default_exec_row.add_suffix(pick_btn)
        # Connect after set_text so initial population doesn't mark dirty
        self._default_exec_row.connect("changed", self._mark_dirty)
        default_group.add(self._default_exec_row)
        page.add(default_group)

        self._rules_group = Adw.PreferencesGroup(
            title="Application URL Handlers",
            description="The first match will be used",
        )
        add_btn = Gtk.Button(icon_name="list-add-symbolic")
        add_btn.add_css_class("flat")
        add_btn.set_tooltip_text("Add rule")
        add_btn.connect("clicked", self._on_add_rule)
        self._rules_group.set_header_suffix(add_btn)

        for h in config.get("handlers", []):
            self._append_row(h)

        page.add(self._rules_group)
        scroll.set_child(page)
        toolbar_view.set_content(scroll)
        self._toast_overlay.set_child(toolbar_view)
        self.set_content(self._toast_overlay)

    def _mark_dirty(self, *_):
        self._save_btn.set_sensitive(True)

    def _append_row(self, handler=None):
        row = HandlerRow(
            handler or {"matcher": "startswith", "pattern": "", "exec": ""},
            self._remove_row,
            self._reorder_row,
            self._mark_dirty,
        )
        self._handler_rows.append(row)
        self._rules_group.add(row)

    def _on_add_rule(self, _):
        self._append_row()
        self._mark_dirty()

    def _remove_row(self, row):
        self._handler_rows.remove(row)
        self._rules_group.remove(row)
        self._mark_dirty()

    def _reorder_row(self, dragged, target):
        src_idx = self._handler_rows.index(dragged)
        dst_idx = self._handler_rows.index(target)
        self._handler_rows.insert(dst_idx, self._handler_rows.pop(src_idx))
        for row in list(self._handler_rows):
            self._rules_group.remove(row)
        for row in self._handler_rows:
            self._rules_group.add(row)
        self._mark_dirty()

    def _on_save(self, *_):
        config = {
            "default": {"exec": self._default_exec_row.get_text()},
            "handlers": [r.get_data() for r in self._handler_rows],
        }
        save_config(config)
        self._save_btn.set_sensitive(False)
        self._toast_overlay.add_toast(Adw.Toast.new("Configuration saved"))


class URLHandlerSettingsApp(Adw.Application):
    def __init__(self):
        super().__init__(application_id="net.sowgro.URLHandler.Configuration")
        self.connect("activate", self._on_activate)

    def _on_activate(self, _):
        SettingsWindow(config=load_config(), application=self).present()


if __name__ == "__main__":
    URLHandlerSettingsApp().run()
